services:
  db:
    container_name: mariadb
    image: mariadb:12.1.2
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - "3306:3306"
    volumes:
      - ./backup/mariadb:/var/lib/mysql
