services:
  db:
    container_name: kafka
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - '3306:3306'
    volumes:
      - ./backup/mariadb:/var/lib/mysql
