services:
  redis:
    container_name: redis
    image: redis:8.4.0-alpine3.22
    ports:
      - "6379:6379"
    volumes:
      - ./backup/certs:/certs
      - ./backup/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
